---
# file: stats config
default:
  transport: udp # udp or tcp
  host: riemann.example.com
  frequency: 10


enabled plugins:
  network:
    - network_io
  disk:
    - disk_io
    - disk_usage
  load:
    - load_avg
  memory:
    - virtual_memory
    - swap_memory


# Specific settings
# module:
#   method:
#     metric:
#       warn: VAL
#       crit: VAL
#       trigger: gt(default)|lt|ignore
#       tags:
#         - any
#         - aditional
#         - tags


